Repository TakhyunKim/closed-caption-extension, pull requests merged in 2022-12, with the labels that each got.

#29 일부 텍스트 번역을 누락하는 버그 수정 🛠
  src/background.ts
Labels: bug, patch

#30 1.2.1 version 적용 🚀
  package.json
  public/manifest.json
Labels: bug, patch

#31 자막 활성화 스위치 스타일 변경
  public/popup.html
  src/popup.css
Labels: enhancement

#32 번역 익스텐션 Youtube 지원
  public/manifest.json
  src/Dom.ts
  src/view/index.ts
Labels: enhancement, refactor

#33 유데미 번역 대상 자막 가져오는 로직 개선
  src/view/index.ts
Labels: bug, enhancement

#34 1.3.0 version 적용
  package.json
  public/manifest.json
Labels: enhancement, minor

#35 README 업데이트 🔖
  README.md
  public/assets/kitty-128.svg
  public/assets/kitty-16.svg
  public/assets/kitty-32.svg
  public/assets/kitty-48.svg
  public/assets/readme/architecture.png
  public/assets/readme/closed-caption.png
  public/assets/readme/kitty.svg
  public/assets/south-korea128.png
  public/assets/south-korea16.png
  public/assets/south-korea32.png
  public/assets/south-korea48.png
  public/manifest.json
Labels: documentation

#36 1.3.1 version 적용 🚀
  package.json
  public/assets/kitty-128.png
  public/assets/kitty-128.svg
  public/assets/kitty-16.png
  public/assets/kitty-16.svg
  public/assets/kitty-32.png
  public/assets/kitty-32.svg
  public/assets/kitty-48.png
  public/assets/kitty-48.svg
  public/manifest.json
Labels: patch

#38 Epic react 지원 🧚
  public/manifest.json
  src/Dom.ts
Labels: enhancement, patch

#39 1.4.0 version 적용 🚀
  package.json
  public/manifest.json
Labels: enhancement, minor

#40 Model Class 테스트 코드 작성 및 coverage github action 추가
  .babelrc
  .github/workflows/unit-test.yml
  .gitignore
  jest.config.js
  package.json
  src/model/model.test.ts
  yarn.lock
Labels: documentation, test

#41 전체 코드 리팩토링 진행
  public/popup.css
  public/popup.ts
  src/api/message/Message.ts
  src/api/message/index.ts
  src/api/storage/Storage.ts
  src/api/storage/index.ts
  src/background.ts
  src/common/const.ts
  src/content.ts
  src/controller/index.ts
  src/model/index.ts
  src/model/types.ts
  src/popup.ts
  src/view/FontSlider.ts
  tsconfig.json
  webpack.config.js
Labels: refactor

#42 unit test github action 동작 시점 변경
  .github/workflows/unit-test.yml
Labels: test
